%% 1a) Find the zeros of the function and its asymptotes
syms x
f=x*exp(1/x); %function
%Finding zeros
solve(f,x); %doesnt have
%zero=1; %for example the intersection point;
%subs(f,x,zero); %subsitute x on f by the point to calculate its image

%Asymptotes
%vertical:limits on the points out of domain. x=a
out_domain=0;
Left_limit=limit(f,x,0,'left'); %0
Right_limit=limit(f,x,0,'right'); %inf
%to draw vertical lines: fplot([a a],interval);

%horizontal: limits on inf and -inf. horizontal_asymptote=b
Limit_Right_inf=limit(f,x,inf);  %inf
Limit_Left_inf=limit(f,x,-inf);  %-inf
%oblique: y=mx+n
Limit_Right_m=limit(f/x,x,inf);          %value of the scope, different from 0
Limit_Right_n=limit(f-Limit_Right_m*x,x,inf); 

Limit_Left_m=limit(f/x,x,-inf);          
Limit_Left_n=limit(f-Limit_Left_m*x,x,-inf); 
%% 1b) Calculate local max and local min, and decreasing, increasing
df=diff(f,x); %first derivative
critical_points=solve(df,x); %Example.Sol: 1
%then calculate their image: 
subs(f,x,1);

%Study the sign of df on the monotonicity intervals
%DONT FORGET TO STUDY ALSO DOMAIN
subs(df,x,-1)  %+
subs(df,x,0.5) %-
subs(df,x,2)   %+
% + and -: maximum; - and +: minimum; + and + or - and -: inflexion point

%f increase(+) on (-inf,0) U (1,inf) and decrease(-) on (0,1)
%Absolute minimum: (1,exp(1))
%% 1c) Study concavity
d2f=diff(f,x,2); %second derivative
inflexion_points=solve(d2f,x); %No sol
%then calculate their image: subs(f,x,d)

%study sign of d2f
%DONT FORGET TO STUDY ALSO DOMAIN
subs(d2f,x,-1) % -
subs(d2f,x,1) %+

%f is concave down (-) on (-inf,0) and concave up (+) on(0,inf)
%% 1d) Plot the function in a suitable interval to see all its features
ezplot(f,[-3 5])
hold on
xline(0)
fplot(x+1,[-3 5])
%% 2a) Draw of the graph of g=x^2, the x=1 and h=(x^2)*(1-x^2)^(1/2) in the first quadrant
syms x
g=x^2;
h=(x^2)*(1-x^2)^(1/2);
fplot(g,[-5 5])
hold on
xline(1)
fplot(h, [-5 5])
%% 2b) Calculate the area
a=0;
b=solve(g-h,x); %sol=0
area=int(g-h,x,0,1);
%% 2c) Calculate the volume generated by revolving this region about the x-axis on (a,b).
volume_x=abs(pi*int((g-h)^2,0,1));
%% d) Calculate the volume generated by revolving the same region about the y-axis (a,b).
volume_y=abs(2*pi*int(x*(g-h),0,1));